import type { NewsArticle, PortfolioItem } from "@/types";

export const MOCK_NEWS: NewsArticle[] = [
  {
    id: "1",
    title: "NVIDIA Surges 4% as AI Chip Demand Breaks Quarterly Records",
    slug: "nvidia-ai-chip-demand-quarterly-records",
    excerpt: "NVIDIA's latest earnings report shows data center revenue tripled year-over-year, driven by insatiable demand for H100 and Blackwell GPUs from major cloud providers.",
    content: "Full article content here...",
    coverImage: "/images/nvidia-news.jpg",
    publishedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    readTime: 4,
    views: 12840,
    author: { name: "Alex Chen", avatarUrl: undefined },
    category: { name: "AI & Tech", slug: "ai-tech", color: "#00C896" },
    tags: ["NVDA", "AI", "earnings", "semiconductors"],
  },
  {
    id: "2",
    title: "Bitcoin Holds $100K Support — Analysts Eye $120K as Next Target",
    slug: "bitcoin-100k-support-120k-target",
    excerpt: "BTC consolidates above the psychologically significant $100,000 level as institutional inflows via spot ETFs continue to absorb selling pressure from long-term holders.",
    content: "Full article content here...",
    publishedAt: new Date(Date.now() - 3 * 3600000).toISOString(),
    readTime: 3,
    views: 28420,
    author: { name: "Maria Santos", avatarUrl: undefined },
    category: { name: "Crypto", slug: "crypto", color: "#F59E0B" },
    tags: ["BTC", "Bitcoin", "price-analysis"],
  },
  {
    id: "3",
    title: "Fed Signals Rate Cuts May Accelerate Amid Cooling Inflation Data",
    slug: "fed-rate-cuts-accelerate-cooling-inflation",
    excerpt: "Federal Reserve Chair Jerome Powell hinted at a more accommodative monetary policy stance following CPI data showing inflation cooling to 2.8%, closer to the 2% target.",
    content: "Full article content here...",
    publishedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    readTime: 5,
    views: 19200,
    author: { name: "James Wilson", avatarUrl: undefined },
    category: { name: "Macro", slug: "macro", color: "#8B5CF6" },
    tags: ["Fed", "inflation", "interest-rates", "macro"],
  },
  {
    id: "4",
    title: "Ethereum ETF Inflows Hit $2.1B in Single Week — Institutional Boom",
    slug: "ethereum-etf-inflows-2b-institutional",
    excerpt: "Spot Ethereum ETFs recorded their strongest weekly inflows since launch, with BlackRock's ETHA leading the pack as institutional investors diversify crypto holdings.",
    content: "Full article content here...",
    publishedAt: new Date(Date.now() - 8 * 3600000).toISOString(),
    readTime: 4,
    views: 31500,
    author: { name: "Sarah Kim", avatarUrl: undefined },
    category: { name: "Crypto", slug: "crypto", color: "#F59E0B" },
    tags: ["ETH", "ETF", "institutional", "BlackRock"],
  },
  {
    id: "5",
    title: "Apple Unveils Vision Pro 2 — Stock Jumps on Pre-Order Numbers",
    slug: "apple-vision-pro-2-stock-pre-orders",
    excerpt: "Apple's second-generation Vision Pro headset sold out within 24 hours of opening pre-orders, suggesting strong consumer demand for spatial computing devices.",
    content: "Full article content here...",
    publishedAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    readTime: 3,
    views: 22100,
    author: { name: "Mike Torres", avatarUrl: undefined },
    category: { name: "AI & Tech", slug: "ai-tech", color: "#00C896" },
    tags: ["AAPL", "Vision Pro", "spatial computing"],
  },
  {
    id: "6",
    title: "Solana Ecosystem Hits 2,000 Active DApps — TVL Reaches $12B",
    slug: "solana-ecosystem-2000-dapps-tvl-12b",
    excerpt: "Solana's DeFi ecosystem continues its explosive growth with total value locked hitting $12 billion and daily transaction counts averaging 50 million.",
    content: "Full article content here...",
    publishedAt: new Date(Date.now() - 18 * 3600000).toISOString(),
    readTime: 4,
    views: 14700,
    author: { name: "Alex Chen", avatarUrl: undefined },
    category: { name: "Crypto", slug: "crypto", color: "#F59E0B" },
    tags: ["SOL", "Solana", "DeFi", "ecosystem"],
  },
];

export const MOCK_PORTFOLIO: PortfolioItem[] = [
  { id: "1", symbol: "BTC", name: "Bitcoin", assetType: "CRYPTO", quantity: 0.45, avgBuyPrice: 82000 },
  { id: "2", symbol: "ETH", name: "Ethereum", assetType: "CRYPTO", quantity: 3.2, avgBuyPrice: 2900 },
  { id: "3", symbol: "NVDA", name: "NVIDIA", assetType: "STOCK", quantity: 10, avgBuyPrice: 850 },
  { id: "4", symbol: "AAPL", name: "Apple", assetType: "STOCK", quantity: 25, avgBuyPrice: 165 },
  { id: "5", symbol: "SOL", name: "Solana", assetType: "CRYPTO", quantity: 20, avgBuyPrice: 120 },
  { id: "6", symbol: "MSFT", name: "Microsoft", assetType: "STOCK", quantity: 8, avgBuyPrice: 380 },
];

export const MOCK_TICKERS = [
  { symbol: "BTC", price: 103420, change: -0.40 },
  { symbol: "ETH", price: 3892, change: 2.10 },
  { symbol: "AAPL", price: 189.30, change: 0.82 },
  { symbol: "NVDA", price: 1087.42, change: 4.21 },
  { symbol: "TSLA", price: 248.50, change: -2.10 },
  { symbol: "SPY", price: 549.20, change: 0.61 },
  { symbol: "SOL", price: 198.00, change: 3.80 },
  { symbol: "META", price: 492.10, change: 1.82 },
  { symbol: "MSFT", price: 415.20, change: 1.24 },
  { symbol: "GOOGL", price: 175.20, change: 0.94 },
  { symbol: "AMZN", price: 184.70, change: 2.41 },
  { symbol: "QQQ", price: 468.90, change: 0.78 },
];

export const MARKET_INDICES = [
  { name: "S&P 500", symbol: "SPX", value: 5489.22, change: 33.82, changePercent: 0.61 },
  { name: "NASDAQ", symbol: "COMP", value: 19826.34, change: 161.49, changePercent: 0.82 },
  { name: "DOW JONES", symbol: "DJI", value: 42410.15, change: 185.72, changePercent: 0.44 },
  { name: "Bitcoin", symbol: "BTC/USD", value: 103420, change: -414.68, changePercent: -0.40 },
];
